# Numpy Basics

In [1]:
import numpy as np

## numpy arrays

In [2]:
np_array = np.array([1,2,3,4])
print(np_array)
print("shape is ",np_array.shape)
type(np_array)

[1 2 3 4]
shape is  (4,)


numpy.ndarray

In [3]:
np_array = np.array([[1,2,3,4],[7,4,8,9]],dtype = float)
print(np_array)
print("shape is ",np_array.shape)
type(np_array)

[[1. 2. 3. 4.]
 [7. 4. 8. 9.]]
shape is  (2, 4)


numpy.ndarray

## array initialisers

In [4]:
# create a array of zeros 
x = np.zeros((4,5)) 
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# create a array of ones
y = np.ones((4,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# create a array with specific value
z = np.full((4,5),4)
z

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [7]:
# create a identity matrix
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# create a np array with random values between 0 and 1
b = np.random.random((3,5))
b

array([[0.09757282, 0.40889038, 0.61399282, 0.42758924, 0.526702  ],
       [0.13771457, 0.26800684, 0.90015108, 0.84418424, 0.441774  ],
       [0.00261387, 0.63829691, 0.92567553, 0.20515415, 0.99927055]])

In [9]:
# create a np array with random int values
c = np.random.randint(low=10,high=100,size=(3,4),)
c

array([[91, 60, 62, 66],
       [45, 69, 64, 75],
       [58, 75, 37, 24]])

In [10]:
# array of evently spaced values --> specifying number of values required
d = np.linspace(10,20,5)
d

array([10. , 12.5, 15. , 17.5, 20. ])

In [11]:
# array of evently spaced values --> specifying steps
e = np.arange(10,30,4)
e

array([10, 14, 18, 22, 26])

## Analysing numpy array

In [12]:
test = np.random.randint(10,30,(3,4))
test

array([[24, 23, 12, 22],
       [10, 18, 17, 13],
       [15, 26, 10, 26]])

In [13]:
# array dimensions
test.shape

(3, 4)

In [14]:
# num of dims
test.ndim

2

In [15]:
# num of elements
test.size

12

In [16]:
# checking data type
test.dtype

dtype('int64')

## Mathematical operations

In [17]:
arr1 = np.random.randint(1,12,size=(3,3))
arr2 = np.random.randint(1,12,size=(3,3))
arr1,arr2

(array([[ 3,  4,  8],
        [ 3,  3,  6],
        [ 5,  4, 10]]),
 array([[ 2,  2,  3],
        [ 4,  2,  9],
        [ 3,  1, 10]]))

In [18]:
print(arr1+arr2) # elementwise addition
print(arr2-arr2) # elementwise subraction
print(arr1*arr1) # elementwise multiplication
print(arr1/arr2) # elementwise division
arr1 @ arr2 # alternative using symbol


[[ 5  6 11]
 [ 7  5 15]
 [ 8  5 20]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[  9  16  64]
 [  9   9  36]
 [ 25  16 100]]
[[1.5        2.         2.66666667]
 [0.75       1.5        0.66666667]
 [1.66666667 4.         1.        ]]


array([[ 46,  22, 125],
       [ 36,  18,  96],
       [ 56,  28, 151]])

In [19]:
# alternative method
print(np.add(arr1,arr2));
print(np.subtract(arr1,arr2));
print(np.multiply(arr1,arr2));
print(np.divide(arr1,arr2));
print(np.matmul(arr1,arr2)) # matrix multiplication

[[ 5  6 11]
 [ 7  5 15]
 [ 8  5 20]]
[[ 1  2  5]
 [-1  1 -3]
 [ 2  3  0]]
[[  6   8  24]
 [ 12   6  54]
 [ 15   4 100]]
[[1.5        2.         2.66666667]
 [0.75       1.5        0.66666667]
 [1.66666667 4.         1.        ]]
[[ 46  22 125]
 [ 36  18  96]
 [ 56  28 151]]


In [20]:
# Transpose
arr1.T


array([[ 3,  3,  5],
       [ 4,  3,  4],
       [ 8,  6, 10]])

## Reshaping

In [21]:
arr = np.arange(12) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
# changing shape
arr = arr.reshape((3,2,2))
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
# flattening numpy array
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
# ravel (return view instead of copy i.e modification will modify original)
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Slicing and Indexing

### 1D array indexing and slicing 

In [25]:
arr = np.array([1,2,3,4,5,6])
arr[0::2] #[start=0 : stop=arr.size : step=1]

array([1, 3, 5])

### multi-dimensional array indexing slicing 

In [26]:
arr_2d = np.random.randint(20,size=(3,2))
arr_2d

array([[ 8,  0],
       [11,  0],
       [11,  3]])

In [27]:
# selecting specific element
print(arr_2d[0][1])
# or
print(arr_2d[0,1])

0
0


In [28]:
# select row
arr_2d[2] #selects 3rd col ot index 2

array([11,  3])

In [29]:
# selcting other than row
arr_2d[:,1] # select 2nd col or index 1

array([0, 0, 3])

## Sorting

In [30]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filter

In [31]:
nums = np.random.randint(10,20,(2,3))
nums

array([[17, 16, 19],
       [15, 10, 14]])

In [32]:
nums[nums%2 == 0] # returns flattened array with values satisfying the condition

array([16, 10, 14])

## Filter with mask

In [33]:
mask = nums%2==0
nums[mask]

array([16, 10, 14])

## np.where()

In [34]:
np.where(nums%2 == 0)

(array([0, 1, 1]), array([1, 1, 2]))